### ISSUE TITLE
Does stund support deploy on two host?

### ISSUE THREAD

**Issue by maytrue** [hanpfei/stund#1]
Certainly.

**Comment by hanpfei** [comment]
Certainly.

**Comment by maytrue** [comment]
-  I have two host with two public ip, how to run stund? Suppose one host with IP1(public), the other with IP2(public).
- If success, can stund return NAT type?

**Comment by hanpfei** [comment]
Assume your two hosts are both allocated a public IP address,  and connect to internet directly.

On host1:
 ./stun_server -b  -h IP1 -u IP2/IP2

On host2:
 ./stun_server -b  -h IP2 -u IP1/IP1

You can see https://my.oschina.net/wolfcs/blog/653833 for more details about the stund.

If success, stund will return NAT type.

**Comment by maytrue** [comment]
Thanks a lot, I will have a try later.

I have read your article, which illustrate stun protocol very clearly.
